#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>

#include "connectionthread.h"

using namespace std;

namespace Ui {
class MainWindow;
}

class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    explicit MainWindow(QWidget *parent = 0);
    ~MainWindow();

public slots:
    void displaySending(QString result);
    void displaySolution(QString result);
    void displayError(QString err);

private slots:
    // This function must be named exactly like this, it's generated by Qt. Kinda. I think.
    void on_SendButton_clicked();

private:
    Ui::MainWindow *ui;
    ConnectionThread conThread;
};

#endif // MAINWINDOW_H
